### ISSUE TITLE
\/ should not be covariant

### ISSUE THREAD

**Issue by fommil** [scalaz/scalaz#1469]
It seems out of place that `\/` (and `Validation`) are covariant in their type parameters when so many other data structures are invariant. Is there a reason for this, or is it just inconsistency that we should fix in a breaking change?

I am writing the chapter on data structures pretty soon, I'll gather other variance inconsistencies that I find in here.

**Comment by TomasMikula** [comment]
I think it's just an oversight that needs to be fixed.

**Comment by puffnfresh** [comment]
Yes, oversight!

**Comment by jdegoes** [comment]
Oversight and already fixed in 8.0.

**Comment by Jacoby6000** [comment]
This might be off-topic for this dicussion, but is disjunction necessary now that scala 2.12's `Either` has a right-bias?  Does disjunction do something that `Either` doesn't?  I think it should probably stay in 7.3 for the sake of people still on 2.11 and simpler migrations between minor releases, but 8.0 could go without it (assuming I'm not missing something).

**Comment by jbgi** [comment]
The plan for 8.0 (and also 7.3) is [to make an Disjunction invariant](https://github.com/scalaz/scalaz/issues/1469). But potentially we could use @TomasMikula [trick](
https://github.com/scalaz/scalaz/issues/1288#issuecomment-290599793) to have zero cost conversion to/from std lib `Either`.

See also @S11001001's [comment on the subject](https://github.com/scalaz/scalaz/issues/1288#issuecomment-290599793)

**Comment by fommil** [comment]
@jacoby6000 the stdlib types still have unsafe methods.

**Comment by tonymorris** [comment]
The stdlib `Either` is still missing some useful libraries and adds unsafe libraries.

The original stdlib `Either` proposal, when written 10 years ago and before forced modification, looked very similar to `\/` today. I'll wait.

**Comment by S11001001** [comment]
Our disjunction *should* be zero-cost wrapper around `Either`, just as @TomasMikula is doing in #1450. But scala/bug#10283 hurts us a lot; we need a minimum of Scala 2.12.

@Jacoby6000 While we may have an **opaque** type in 8 suchly, we will *not* simply suggest using `Either` instead, or provide a transparent alias, for reasons already stated.

@fommil To provide another answer to your question, in 7.x, things generally started out covariant. Then we had scala/bug#2066 to deal with. Then we had [the lack of variance variables or *something*](https://failex.blogspot.com/2016/09/the-missing-diamond-of-scala-variance.html#markdown-header-whence-monad-transformer-variance) to help us deal with variance in higher kinds, so it was easier to just drop variance wherever it got even a little troublesome.  I don't know how you want to treat subtyping in the book, since your readers are probably used to designing with it (but, in all honesty, have probably not thought through all subtyping's implications—surely they would have run screaming in the opposite direction if they had) but I can tell you that part of the scalaz user philosophy is to abandon subtyping entirely as a design tool, preferring other, saner forms of polymorphism.

**Comment by fommil** [comment]
I'd like to drop subtyping but I think I need more examples of where it's broken in scala than what I have.

**Comment by TomasMikula** [comment]
Why was this closed?

**Comment by fommil** [comment]
@TomasMikula Kenji wants to release pretty soon and this is a mammoth task. If anybody else wants to pick it up for 7.3 I'd be delighted to reopen it! I think the way to do it would be to write a scalafix rule to migrate all uses of `-\/` and `\/-` to the variant that takes the type parameter of the other side (like the `.left` / `.right` syntax)

**Comment by TomasMikula** [comment]
I'm taking a stab at it. It's more complicated than that, though: it forces to make other data types (like `These`, `Validation`, `Either3`, `Task`, ...) invariant as well.

**Comment by TomasMikula** [comment]
https://github.com/scalaz/scalaz/blob/b59aff7e254d53107cc194bd011cfad18e258297/core/src/main/scala/scalaz/package.scala#L349

what? :rofl:

**Comment by fommil** [comment]
@TomasMikula yup, I think you're heading down the path I started on... I'd consider it a win if *any* of these other data types are made invariant. LOL at the example, there is certainly some stuff there I'd love to see removed.

**Comment by fommil** [comment]
CURSE YOU, YOU PRESSED OPEN AT THE SAME TIME AS ME!! :stuck_out_tongue:

**Comment by fommil** [comment]
![](https://media.giphy.com/media/3oEdv06Kkj7PVgt6Uw/giphy.gif)
